export default {
	users: [
		{
			name: "@1:worqapp.com",
			user_type: null,
			is_guest: 0,
			admin: 0,
			deactivated: 0,
			shadow_banned: false,
			displayname: "1",
			avatar_url: null,
		},
		{
			name: "@appmanager:worqapp.com",
			user_type: null,
			is_guest: 0,
			admin: 1,
			deactivated: 0,
			shadow_banned: false,
			displayname: "AppManager",
			avatar_url: null,
		},
		{
			name: "@5dd1a7aa208ea0106f84fbd2:worqapp.com",
			user_type: null,
			is_guest: 0,
			admin: 0,
			deactivated: 0,
			shadow_banned: false,
			displayname: "worqapptester1",
			avatar_url: null,
		},
		{
			name: "@5e4652d84e1357aa16f00f5d:worqapp.com",
			user_type: null,
			is_guest: 0,
			admin: 0,
			deactivated: 0,
			shadow_banned: false,
			displayname: "Wan The Builder",
			avatar_url: "mxc://worqapp.com/mfEEEzsCJHfWqdWNrCMsvUVk",
		},
	],
}
